name: 'Cross-Platform SSH Server'
description: 'Sets up an SSH server on Windows, Linux, or macOS with configurable keys and automatic cleanup'

branding:
  icon: 'server'
  color: 'blue'

inputs:
  ssh-jump-user:
    required: false
    default: ''
    description: ''

  ssh-jump-host:
    required: true
    description: 'SSH jump host server for tunneling Docker daemon access'

  ssh-jump-port:
    required: false
    default: '22'
    description: 'SSH jump host port for tunneling Docker daemon access'

  ssh-jump-private-key:
    required: false
    default: ''
    description: ''

  ssh-jump-host-key:
    required: true
    description: 'SSH host key for jump server verification (known_hosts format)'

  ssh-user:
    description: 'SSH username. Use :current to get the current user name (default: :current)'
    required: false
    default: ':current'

  ssh-port:
    description: 'SSH server port (default: 2222)'
    required: false
    default: '2222'

  authorized-keys:
    description: 'Authorized public keys (one per line)'
    required: false

  use-actor-ssh-keys:
    description: 'Whether to authorize the public SSH keys of the user triggering the workflow'
    required: false
    default: 'true'

  wait-timeout:
    description: ''
    required: false
    default: '1800'

runs:
  using: 'composite'
  steps:
    - name: Configure SSH daemon
      id: sshd
      uses: lexbritvin/setup-sshd-action@main
      with:
        port: ${{ inputs.ssh-port }}
        authorized-keys: ${{ inputs.ssh-authorized-keys }}
        use-actor-ssh-keys: ${{ inputs.use-actor-ssh-keys }}

    - name: Prepare jump host
      id: jump-info
      shell: bash
      run: |
        JUMP_USER="github-runner-${{ github.run_id }}-$RANDOM"
        echo "username=$JUMP_USER" >> $GITHUB_OUTPUT
        echo "remote-forwards=$JUMP_USER:${{ steps.sshd.outputs.port }}:${{ steps.sshd.outputs.hostname }}:${{ steps.sshd.outputs.port }}" >> $GITHUB_OUTPUT
        echo "hostname=$JUMP_USER" >> $GITHUB_OUTPUT

    - name: Establish SSH tunnel
      id: sshd-tunnel
      uses: lexbritvin/ssh-port-forward-action@main
      with:
        host: ${{ inputs.ssh-jump-host }}
        username: "${{ steps.jump-info.outputs.username }}"
        port: "${{ inputs.ssh-jump-port }}"
        remote-forwards: "${{ steps.jump-info.outputs.remote-forwards }}"
        known-hosts: ${{ inputs.ssh-jump-host-key }}

    - name: Output connection information
      id: help-msg
      shell: bash
      run: |
        SSH_JUMP="${{ steps.jump-info.outputs.username }}@${{ inputs.ssh-jump-host }}:${{ inputs.ssh-jump-port }}"
        SSH_LOGIN="${{ steps.sshd.outputs.username }}@${{ steps.jump-info.outputs.hostname }}"
        SSH_PORT="${{ steps.sshd.outputs.port }}"
        SSH_SCRIPT="cd $PWD && exec \\\$SHELL -l"
        WORKING_DIR="$PWD"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          WORKING_DIR="$(cygpath -w "$PWD" 2>/dev/null || echo "$PWD")"
          export SSH_SCRIPT="powershell -Command \"Set-Location '$WORKING_DIR'; powershell\""
        fi
        
        SSH_BASE="-J $SSH_JUMP -p $SSH_PORT $SSH_LOGIN"
        SSH_SHORT="ssh $SSH_BASE"
        SSH_FULL="$SSH_SHORT -t \"$SSH_SCRIPT\""
        
        {
          echo 'help-message<<EOF'
          cat << HELP_EOF
        \033[1;36m📝 Debug Session Information\033[0m
        
        \033[1;31m⚠️ IMPORTANT ⚠️\033[0m
            - SSH access is limited to the keys provided in \033[1mauthorized-keys\033[0m 
              and a GitHub user who started this debug session if \033[1muse-actor-ssh-keys\033[0m is given.
            - Your GitHub account's SSH keys will be used for authentication if \033[1muse-actor-ssh-keys\033[0m is given.
            TODO - Session will automatically end after disconnect
            - Maximum session time is 30 minutes
            TODO - All changes are temporary and will be lost after session ends
        
        \033[1;36m===============================================================\033[0m
        
        \033[1;32m🔗 1. Connect with SSH:\033[0m
              \033[1m$SSH_BASE\033[0m
              \033[1m$SSH_FULL\033[0m
        
        \033[1;32m🔄 2. Forward a port:\033[0m
              \033[1mssh -L 3000:localhost:8080 $SSH_BASE\033[0m
        
        \033[1;32m💻 3. Connect over SSH using VS Code for full developer experience\033[0m
              - Open VS Code
              - Install Remote SSH extension if not installed
              - Select 'Remote-SSH: Connect to Host...'
              - Enter the SSH command from step 1
              - Select the session to connect and open $WORKING_DIR
              VS Code on remote environment will allow you to forward any ports.
        
        \033[1;32m🚀 Happy coding! 💻 🎉\033[0m
        HELP_EOF
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - name: Connection info
      shell: bash
      env:
        HELP_MESSAGE: ${{ steps.help-msg.outputs.help-message }}
      run: |
        printf '%b\n' "$HELP_MESSAGE"

    - name: 📄 Wait for Finish
      uses: lexbritvin/wait-for-action@main
      with:
        condition-type: 'file'
        file-path: './finish-debug'
        timeout-seconds: ${{ inputs.wait-timeout }}
        poll-interval-seconds: '60'
        detached: 'true'
