name: 'Cross-Platform SSH Server'
description: 'Sets up an SSH server on Windows, Linux, or macOS with configurable keys and automatic cleanup'

branding:
  icon: 'server'
  color: 'blue'

inputs:
  ssh-jump-user:
    required: false
    default: ''
    description: ''

  ssh-jump-host:
    required: true
    description: 'SSH jump host server for tunneling Docker daemon access'

  ssh-jump-port:
    required: false
    default: '22'
    description: 'SSH jump host port for tunneling Docker daemon access'

  ssh-jump-private-key:
    required: false
    default: ''
    description: ''

  ssh-jump-host-key:
    required: true
    description: 'SSH host key for jump server verification (known_hosts format)'

  ssh-user:
    description: 'SSH username. Use :current to get the current user name (default: :current)'
    required: false
    default: ':current'

  ssh-port:
    description: 'SSH server port (default: 2222)'
    required: false
    default: '2222'

  authorized-keys:
    description: 'Authorized public keys (one per line)'
    required: false

  use-actor-ssh-keys:
    description: 'Whether to authorize the public SSH keys of the user triggering the workflow'
    required: false
    default: 'true'

  wait-timeout:
    description: ''
    required: false
    default: '1800'

runs:
  using: 'composite'
  steps:
    - name: Configure SSH daemon
      id: sshd
      uses: lexbritvin/setup-sshd-action@main
      with:
        port: ${{ inputs.ssh-port }}
        authorized-keys: ${{ inputs.ssh-authorized-keys }}
        use-actor-ssh-keys: ${{ inputs.use-actor-ssh-keys }}

    - name: Prepare jump host
      id: jump-info
      shell: bash
      run: |
        JUMP_USER="github-runner-${{ github.run_id }}-$RANDOM"
        echo "username=$JUMP_USER" >> $GITHUB_OUTPUT
        echo "remote-forwards=$JUMP_USER:${{ steps.sshd.outputs.port }}:${{ steps.sshd.outputs.hostname }}:${{ steps.sshd.outputs.port }}" >> $GITHUB_OUTPUT
        echo "hostname=$JUMP_USER" >> $GITHUB_OUTPUT

    - name: Establish SSH tunnel
      id: sshd-tunnel
      uses: lexbritvin/ssh-port-forward-action@main
      with:
        host: ${{ inputs.ssh-jump-host }}
        username: "${{ steps.jump-info.outputs.username }}"
        port: "${{ inputs.ssh-jump-port }}"
        remote-forwards: "${{ steps.jump-info.outputs.remote-forwards }}"
        known-hosts: ${{ inputs.ssh-jump-host-key }}

    - name: Output connection information
      shell: bash
      run: |
        SSH_JUMP="${{ steps.jump-info.outputs.username }}@${{ inputs.ssh-jump-host }}:${{ inputs.ssh-jump-port }}"
        SSH_LOGIN="${{ steps.sshd.outputs.username }}@${{ steps.jump-info.outputs.hostname }}"
        SSH_PORT="${{ steps.sshd.outputs.port }}"
        SSH_SCRIPT="cd $PWD && exec \\\$SHELL -l"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          export SSH_SCRIPT="powershell -Command \"Set-Location '$(cygpath -w "$PWD" 2>/dev/null || echo "$PWD")'; powershell\""
        fi
        
        echo "ssh -J $SSH_JUMP -p $SSH_PORT $SSH_LOGIN -t \"$SSH_SCRIPT\""

    - name: Connection info
      shell: bash
      env:
        DEBUG_INFO: |
          [1;36m📝 Debug Session Information[0m
          
          [1;31m⚠️ IMPORTANT ⚠️[0m
              - SSH access is limited to the keys provided in [1mauthorized-keys[0m 
                and a GitHub user who started this debug session if [1muse-actor-ssh-keys[0m is given.
              - Your GitHub account's SSH keys will be used for authentication if [1muse-actor-ssh-keys[0m is given.
              TODO - Session will automatically end after disconnect
              - Maximum session time is 30 minutes
              TODO - All changes are temporary and will be lost after session ends
          
          [1;36m===============================================================[0m
          
          [1;32m🔗 1. Connect with SSH:[0m
                [1m${{ steps.tmate.outputs.ssh-command }}[0m
          
          [1;32m🔄 2. Forward a port:[0m
                [1mssh -L 3000:localhost:8080 ${{ steps.tmate.outputs.ssh-address }}[0m
          
          [1;32m💻 3. Connect over SSH using VS Code for full developer experience[0m
                - Open VS Code
                - Install Remote SSH and Go extensions if not installed
                - Select 'Remote-SSH: Connect to Host...'
                - Enter the SSH command from step 1
                VS Code on remote environment will allow you to forward any ports.
          
          [1;32m🚀 Happy coding! 💻 🎉[0m
      run: |
        printf '%s\n' "$DEBUG_INFO"

#    - name: 🛠 Set up tmate session 🛠
#      id: tmate
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true

    - name: 📄 Wait for Finish
      uses: lexbritvin/wait-for-action@main
      with:
        condition-type: 'file'
        file-path: './finish-debug'
        timeout-seconds: ${{ inputs.wait-timeout }}
        poll-interval-seconds: '60'
        detached: 'true'
