name: Debug Workflow Example

on:
  push:
    branches: [ main ]

env:
  SSH_JUMP_USER: ':generate'
  SSH_JUMP_FORWARD: ':generate'
  SSH_JUMP_SERVER: ssh-j.com
  SSH_JUMP_HOST_KEY: |
    ssh-j.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIiyFQuTwegicQ+8w7dLA7A+4JMZkCk8TLWrKPklWcRt

jobs:
  debug:
    name: SSH Debug
    runs-on: ubuntu-latest
#    runs-on: windows-latest
    steps:
      - name: Run SSH Debug
        uses: lexbritvin/ssh-debug-action@main
        with:
          ssh-jump-user: ${{ env.SSH_JUMP_USER }}
          ssh-jump-forward: ${{ env.SSH_JUMP_FORWARD }}
          ssh-jump-host: ${{ env.SSH_JUMP_SERVER }}
          ssh-jump-host-keys: ${{ env.SSH_JUMP_HOST_KEY }}
          use-actor-ssh-keys: 'true'
