name: Debug Workflow Example

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Debug with SSH in OS'
        required: false
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

env:
  SSH_JUMP_HOST: ssh-j.com
  SSH_JUMP_PORT: '22'
  SSH_JUMP_USER: ':generate'
  SSH_JUMP_FORWARD: ':generate'
  SSH_JUMP_HOST_KEYS: |
    ssh-j.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIiyFQuTwegicQ+8w7dLA7A+4JMZkCk8TLWrKPklWcRt

jobs:
  debug:
    name: SSH Debug
    runs-on: ${{ inputs.os }}
    steps:
      - name: Run SSH Debug
        uses: lexbritvin/ssh-debug-action@main
        with:
          ssh-jump-host: ${{ env.SSH_JUMP_HOST }}
          ssh-jump-port: ${{ env.SSH_JUMP_PORT }}
          ssh-jump-user: ${{ env.SSH_JUMP_USER }}
          ssh-jump-host-keys: ${{ env.SSH_JUMP_HOST_KEYS }}
          ssh-jump-forward: ${{ env.SSH_JUMP_FORWARD }}
          use-actor-ssh-keys: 'true'
